import VueMatomo from 'vue-matomo'
import { router } from './router'
import { store } from './store'
import { namespacedTypes as persistedTypes } from '@/store/modules/settings'

/**
 * Overwrite the setConsentGiven() and forgetConsentGive() methods of Matomo
 * to persist their choice in the settings store
 *
 * @param {{}} matomo functions/object
 */
function extendMatomo(matomo) {
    const originalSetConsentGive = matomo.setConsentGiven
    const originalForgetConsentGiven = matomo.forgetConsentGiven

    matomo.setConsentGiven = function() {
        store.commit({
            type: persistedTypes.SET_ALLOW_TRACKING,
            value: true
        })

        originalSetConsentGive.apply(this, arguments)
    }

    matomo.forgetConsentGiven = function() {
        store.commit({
            type: persistedTypes.SET_ALLOW_TRACKING,
            value: false
        })

        originalForgetConsentGiven.apply(this, arguments)
    }

    return matomo
}

let matomo
export default {
    install(Vue) {
        Vue.use(VueMatomo, {
            // Configure your matomo server and site by providing
            host: 'https//127.0.0.1:8001',
            siteId: 1,

            // Changes the default .js and .php endpoint's filename
            // Default: 'piwik'
            // trackerFileName: 'matomo',

            // Overrides the autogenerated tracker endpoint entirely
            // Default: undefined
            // trackerUrl: 'https://example.com/whatever/endpoint/you/have',
            trackerUrl: 'http://127.0.0.1:8001/matomo.php',

            // Enables link tracking on regular links. Note that this won't
            // work for routing links (ie. internal Vue router links)
            // Default: true
            enableLinkTracking: true,

            // Require consent before sending tracking information to matomo
            // Default: false
            requireConsent: true,

            // Whether to track the initial page view
            // Default: true
            trackInitialView: true,

            // Whether or not to log debug information
            // Default: false
            debug: false
        })

        matomo = Vue.prototype.$matomo = extendMatomo(Vue.prototype.$matomo)

        router.afterEach((to, from) => {
            matomo.setCustomUrl(to.fullPath)
            matomo.trackPageView(to.name)
        })
    }
}

export { matomo }
