import VueMatomo from 'vue-matomo'
import { router } from './router'

export default {
    install(Vue) {
        Vue.use(VueMatomo, {
            // Configure your matomo server and site by providing
            host: 'https//127.0.0.1:8001',
            siteId: 1,

            // Changes the default .js and .php endpoint's filename
            // Default: 'piwik'
            // trackerFileName: 'matomo',

            // Overrides the autogenerated tracker endpoint entirely
            // Default: undefined
            // trackerUrl: 'https://example.com/whatever/endpoint/you/have',
            trackerUrl: 'http://127.0.0.1:8001/matomo.php',

            // Enables link tracking on regular links. Note that this won't
            // work for routing links (ie. internal Vue router links)
            // Default: true
            enableLinkTracking: true,

            // Require consent before sending tracking information to matomo
            // Default: false
            requireConsent: false,

            // Whether to track the initial page view
            // Default: true
            trackInitialView: true,

            // Whether or not to log debug information
            // Default: false
            debug: true
        })

        router.afterEach((to, from) => {
            const matomo = Vue.prototype.$matomo
            matomo.setCustomUrl(to.fullPath)
            matomo.trackPageView(to.name)
        })
    }
}
